# Generated by Django 3.2.23 on 2024-01-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batchname', models.CharField(default=1, max_length=100)),
                ('Fromtime', models.CharField(max_length=100)),
                ('Totime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('paymentdate', models.CharField(max_length=100)),
                ('paymentstatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.login')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutname', models.CharField(default=1, max_length=100)),
                ('category', models.CharField(default=1, max_length=100)),
                ('duration', models.CharField(default=1, max_length=100)),
                ('exercise', models.CharField(default=1, max_length=100)),
                ('sets', models.CharField(default=1, max_length=100)),
                ('reps', models.CharField(default=1, max_length=100)),
                ('resttime', models.CharField(default=1, max_length=100)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.login')),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=100)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.trainer')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user')),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(default=1, max_length=100)),
                ('email', models.CharField(default=1, max_length=100)),
                ('password', models.CharField(default=1, max_length=100)),
                ('contactno', models.CharField(default=1, max_length=100)),
                ('place', models.CharField(default=1, max_length=100)),
                ('post', models.CharField(default=1, max_length=100)),
                ('pin', models.CharField(default=1, max_length=100)),
                ('latitude', models.CharField(default=1, max_length=100)),
                ('longitude', models.CharField(default=1, max_length=100)),
                ('openingtime', models.CharField(default=1, max_length=100)),
                ('closingtime', models.CharField(default=1, max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.login')),
            ],
        ),
        migrations.CreateModel(
            name='Requestt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('requeststate', models.CharField(max_length=100)),
                ('requeststatus', models.CharField(default=1, max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.trainer')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user')),
            ],
        ),
        migrations.CreateModel(
            name='Questinare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=100)),
                ('answers', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemdescription', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('SHOP', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymenttype', models.CharField(max_length=100)),
                ('paymentdate', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ordersub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.order')),
                ('PRODUCT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='SHOP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.shops'),
        ),
        migrations.AddField(
            model_name='order',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user'),
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('alergies', models.CharField(max_length=100)),
                ('medicalhistory', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.trainer')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('breakfast', models.CharField(default=1, max_length=100)),
                ('lunch', models.CharField(default=1, max_length=100)),
                ('dinner', models.CharField(default=1, max_length=100)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=100)),
                ('complaintdate', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('replydate', models.CharField(max_length=100)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.trainer')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.trainer')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('PRODUCT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.product')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.user')),
            ],
        ),
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('BATCH', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.batch')),
                ('REQUEST', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.requestt')),
                ('TRAINER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitWell.trainer')),
            ],
        ),
    ]
