# Generated by Django 3.2.23 on 2024-01-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitWell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
