# Generated by Django 3.2.23 on 2024-01-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitWell', '0002_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
