# Generated by Django 3.2.23 on 2024-02-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitWell', '0004_auto_20240128_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='TRAINER',
        ),
    ]
