# Generated by Django 3.2.23 on 2024-02-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitWell', '0005_remove_complaint_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='replydate',
            field=models.CharField(default='0000-00-00', max_length=100),
        ),
    ]
