# Generated by Django 3.2.23 on 2024-02-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitWell', '0006_auto_20240203_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='receiver',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='sender',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='time',
        ),
    ]
