# Generated by Django 3.2.23 on 2024-02-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitWell', '0007_auto_20240212_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='tips',
            field=models.CharField(max_length=1000),
        ),
    ]
